### HTTP ###
domain: 0.0.0.0

http-port: 8080

http-secured: false

http-allowed-origins:
  - "http://127.0.0.1:4321"

### DATABASE ###
db-default-queuery-timeout: 5s

db-max-search-page-size: 100

db-skip-post-connection: true

### AUTH ###
access-token-ttl: 10m

refresh-token-ttl: 336h # 14 days

token-audience:
  - "urn:api:auth"

self-audience: "urn:api:auth" # Audience for this service (must exists in token-audience)

### CACHE ###
cache-pool-timeout: 3s

cache-operation-timeout: 1s

cache-ttl: 0

### DEBUG ####
debug-mode: true

debug-safe-db-scans: true

debug-log-db-queries: true

# If not empty then this IP will be used to get all users location.
# Designed for debugging, cuz location provider will return error if IP is local, e.g. 127.0.0.1
debug-location-ip: 8.8.8.8

### APP ###
service-id: cb663674-803e-4b06-bfeb-87c5cc86383e

user-activation-token-ttl: 24h

password-reset-token-ttl: 1h

# This url will be specified in email from "forgot-password" endpoint.
# Should lead to the frontend (e.g. reset-password page).
# Password reset token will be added in query params for this url (in passwordResetToken param).
password-reset-redirect-url: https://localhost:8080/v1/example-redirect-url

show-logs: true

trace-logs: true

### EMAIL ###

smtp-host: smtp.gmail.com

smtp-port: 587

### SENTRY ###

sentry-trace-sample-rate: 0.1 # 10%

